changelog:
  exclude:
    labels:
      - internal-only
      - skip-changelog
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Additions
      labels:
        - kind:additive
    - title: Fixes
      labels:
        - kind:bug
    - title: Docs
      labels:
        - kind:docs
    - title: CI and release
      labels:
        - kind:ci
        - kind:packaging
    - title: Soft deprecations
      labels:
        - kind:soft-deprecated
    - title: Internal changes
      labels:
        - kind:internal
